### ISSUE TITLE
S3 backend support?

### ISSUE THREAD

**Issue by CodaBool** [rootsami/terradrift#20]
I could be missing something but it appears from the examples that there is no S3 backend support. Is that the case?

I feel it's a common use case and would be a great addition here.
There is really not any competition in this area besides `driftctl` and it's a fantastic area to improve on Terraform.

**Comment by rootsami** [comment]
It works perfectly with any backend supported by terraform. It's designed to work on any regular terraform codebase with all its features. 

The examples are only for explanations and simple testings. Thanks @CodaBool

**Comment by CodaBool** [comment]
can you provide an example of what the config.yaml file should look like then?

If my config.yaml looked like this what would I need to change?

```yml
stacks:
  - name: NAME_HERE
    path: ./
    backend: tfstate+s3://BUCKET_NAME/BUCKET_KEY/terraform.tfstate
```

Then I imagine my command would look like this right? Assuming my current working directory is where my terraform files are located.

`./terradrift-cli --config ./config.yaml`
